### ISSUE TITLE
安装内核时找不到文件

### ISSUE THREAD

**Issue by zombie110year** [laixintao/jupyter-dot-kernel#3]
尊敬的开发者:

您好!

我使用 pip 安装了 `dot_kernel` , 使用您提供的脚本 `install-dot-kernel` 安装, 提示找不到文件. 使用 `locate` 命令搜索 `dot_kernel` 找到以下内容, 使用 `jupyter kernelspec install dot_kernel` 无法找到文件.

请问应该怎样才能正确安装, 是否更改了名称?

---

使用 `install-dot-kernel`

```sh
jupyter@iZwz9cixaslir6cf0zd9lyZ:~$ install-dot-kernel
Traceback (most recent call last):
  File "/home/jupyter/anaconda3/bin/jupyter-kernelspec", line 11, in <module>
    sys.exit(KernelSpecApp.launch_instance())
  File "/home/jupyter/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/jupyter/anaconda3/lib/python3.6/site-packages/jupyter_client/kernelspecapp.py", line 273, in start
    return self.subapp.start()
  File "/home/jupyter/anaconda3/lib/python3.6/site-packages/jupyter_client/kernelspecapp.py", line 143, in start
    replace=self.replace,
  File "/home/jupyter/anaconda3/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 346, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/home/jupyter/anaconda3/lib/python3.6/shutil.py", line 309, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: 'dot_kernel_spec'
```

使用 `jupyter kernelspec install dot_kernel`

```sh
jupyter@iZwz9cixaslir6cf0zd9lyZ:~$ jupyter kernelspec install dot_kernel
Traceback (most recent call last):
  File "/home/jupyter/anaconda3/bin/jupyter-kernelspec", line 11, in <module>
    sys.exit(KernelSpecApp.launch_instance())
  File "/home/jupyter/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/jupyter/anaconda3/lib/python3.6/site-packages/jupyter_client/kernelspecapp.py", line 273, in start
    return self.subapp.start()
  File "/home/jupyter/anaconda3/lib/python3.6/site-packages/jupyter_client/kernelspecapp.py", line 143, in start
    replace=self.replace,
  File "/home/jupyter/anaconda3/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 346, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/home/jupyter/anaconda3/lib/python3.6/shutil.py", line 309, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: 'dot_kernel'
```

使用 `locate` 命令搜索 `dot_kernel` (已提前 sudo updatedb)

```sh
jupyter@iZwz9cixaslir6cf0zd9lyZ:~$ locate dot_kernel
/home/jupyter/.cache/pip/wheels/be/4b/a7/8faefd17549cdac8c5466be9bdecf308b11bd02fde4bab4dbc/dot_kernel-0.1.5-cp36-none-any.whl
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel-0.1.5.dist-info
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel/__init__.py
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel/__main__.py
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel/__pycache__
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel/imgsize.py
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel/kernel.py
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel/__pycache__/__init__.cpython-36.pyc
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel/__pycache__/__main__.cpython-36.pyc
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel/__pycache__/imgsize.cpython-36.pyc
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel/__pycache__/kernel.cpython-36.pyc
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel-0.1.5.dist-info/INSTALLER
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel-0.1.5.dist-info/METADATA
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel-0.1.5.dist-info/RECORD
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel-0.1.5.dist-info/WHEEL
/home/jupyter/anaconda3/lib/python3.6/site-packages/dot_kernel-0.1.5.dist-info/top_level.txt
```

**Comment by SmirkCao** [comment]
- git clone https://github.com/laixintao/jupyter-dot-kernel.git
- cd jupyter-dot-kernel
- jupyter kernelspec install dot_kernel_spec --user

**Comment by zombie110year** [comment]
> 
> 
>     * git clone https://github.com/laixintao/jupyter-dot-kernel.git
> 
>     * cd jupyter-dot-kernel
> 
>     * jupyter kernelspec install dot_kernel_spec --user

It works, THANX! 👍

**Comment by yanqd0** [comment]
The `dot_kernel_spec` should be package into the PyPI artifact.
